/**
 * @fileoverview Shared stop-word policy for deterministic non-safety language handling.
 */

import type { LanguageProfileId, LanguageTokenDomain } from "./contracts";
import { resolveLanguageProfileId } from "./languageProfiles";

const COMMON_EN_STOP_WORDS = new Set([
  "a",
  "an",
  "and",
  "are",
  "for",
  "from",
  "how",
  "is",
  "it",
  "me",
  "my",
  "of",
  "on",
  "that",
  "the",
  "this",
  "to",
  "was",
  "we",
  "what",
  "when",
  "where",
  "who",
  "why",
  "with",
  "you",
  "your"
]);

const COMMON_ES_STOP_WORDS = new Set([
  "a",
  "al",
  "como",
  "c\u00f3mo",
  "con",
  "de",
  "del",
  "el",
  "ella",
  "en",
  "es",
  "esta",
  "este",
  "la",
  "las",
  "le",
  "lo",
  "los",
  "me",
  "mi",
  "mis",
  "para",
  "por",
  "que",
  "qui\u00e9n",
  "qué",
  "se",
  "su",
  "sus",
  "te",
  "tu",
  "un",
  "una",
  "y",
  "yo"
]);

const DOMAIN_STOP_WORDS: Record<LanguageProfileId, Record<LanguageTokenDomain, ReadonlySet<string>>> = {
  generic_en: {
    conversation_topic: new Set([
      ...COMMON_EN_STOP_WORDS,
      "about",
      "agentbigbrain",
      "also",
      "back",
      "bigbrain",
      "chat",
      "could",
      "discuss",
      "go",
      "have",
      "here",
      "into",
      "just",
      "let",
      "lets",
      "let's",
      "need",
      "next",
      "now",
      "please",
      "show",
      "should",
      "tell",
      "there",
      "thread",
      "today",
      "tomorrow",
      "topic",
      "week",
      "will",
      "would",
      "yesterday"
    ]),
    contextual_recall: new Set([
      ...COMMON_EN_STOP_WORDS,
      "any",
      "back",
      "been",
      "but",
      "can",
      "did",
      "got",
      "had",
      "has",
      "have",
      "hey",
      "her",
      "his",
      "into",
      "its",
      "just",
      "later",
      "like",
      "need",
      "next",
      "now",
      "our",
      "out",
      "same",
      "she",
      "them",
      "then",
      "they",
      "thing",
      "those",
      "today",
      "want",
      "would"
    ]),
    planning_query: new Set([
      ...COMMON_EN_STOP_WORDS,
      "about",
      "at",
      "did",
      "do",
      "does",
      "in",
      "now",
      "related",
      "relation"
    ]),
    episode_planning_query: new Set([
      ...COMMON_EN_STOP_WORDS,
      "did",
      "does",
      "had",
      "has",
      "have",
      "their",
      "them",
      "they"
    ]),
    episode_linking: new Set([
      ...COMMON_EN_STOP_WORDS,
      "after",
      "around",
      "assistant",
      "before",
      "contact",
      "did",
      "down",
      "entity",
      "episode",
      "event",
      "had",
      "has",
      "have",
      "just",
      "later",
      "loop",
      "need",
      "now",
      "out",
      "situation",
      "some",
      "still",
      "their",
      "them",
      "there",
      "thing",
      "thread",
      "were"
    ]),
    semantic_concepts: new Set([
      ...COMMON_EN_STOP_WORDS,
      "about",
      "action",
      "actions",
      "allow",
      "allows",
      "always",
      "been",
      "blocked",
      "could",
      "have",
      "has",
      "into",
      "never",
      "should",
      "task",
      "using",
      "will",
      "would",
      "were",
      "which"
    ])
  },
  generic_es: {
    conversation_topic: new Set([
      ...COMMON_ES_STOP_WORDS,
      "agentbigbrain",
      "bigbrain",
      "chat",
      "dime",
      "hablemos",
      "hola",
      "hoy",
      "luego",
      "mañana",
      "necesito",
      "podemos",
      "porfa",
      "quiero",
      "tema",
      "volver"
    ]),
    contextual_recall: new Set([
      ...COMMON_ES_STOP_WORDS,
      "algo",
      "ayer",
      "bien",
      "después",
      "eso",
      "esta",
      "esto",
      "fue",
      "había",
      "hizo",
      "luego",
      "mismo",
      "necesito",
      "otra",
      "otro",
      "pasó",
      "porque",
      "quiere",
      "si",
      "sigue",
      "también"
    ]),
    planning_query: new Set([
      ...COMMON_ES_STOP_WORDS,
      "ahora",
      "relacion",
      "relación",
      "relacionado",
      "sobre"
    ]),
    episode_planning_query: new Set([
      ...COMMON_ES_STOP_WORDS,
      "despues",
      "después",
      "estaba",
      "estuvo",
      "habia",
      "había",
      "tenía",
      "tenia"
    ]),
    episode_linking: new Set([
      ...COMMON_ES_STOP_WORDS,
      "accidente",
      "asunto",
      "cosa",
      "después",
      "episodio",
      "evento",
      "historia",
      "luego",
      "necesita",
      "pasó",
      "sigue",
      "situación",
      "situacion",
      "tema"
    ]),
    semantic_concepts: new Set([
      ...COMMON_ES_STOP_WORDS,
      "acciones",
      "debería",
      "deberia",
      "nunca",
      "permite",
      "siempre",
      "tarea",
      "usar"
    ])
  }
};

/**
 * Returns the stop-word set for one deterministic non-safety language domain.
 *
 * @param domain - Bounded tokenization domain.
 * @param profileId - Optional language profile override.
 * @returns Stable stop-word set for the requested domain/profile.
 */
export function getStopWordsForLanguageDomain(
  domain: LanguageTokenDomain,
  profileId?: LanguageProfileId
): ReadonlySet<string> {
  const resolvedProfileId = resolveLanguageProfileId(profileId);
  return DOMAIN_STOP_WORDS[resolvedProfileId][domain];
}
